### ISSUE TITLE
Feedback for ICE 3.20

### ISSUE THREAD

**Issue by Elbullazul** [bluedxca93/ice#1]
hi, this is a great theme @bluedxca93 !

I noticed a few bugs while exploring the theme:

**Backdrop SSD buttons retain the original ambiance look**
![virtualbox_fedora 24 stable_26_09_2016_14_05_31](https://cloud.githubusercontent.com/assets/15310985/18846149/9f23a502-83f2-11e6-9a68-6298e4dd0571.png)

**The round button has a square border**
![virtualbox_fedora 24 stable_26_09_2016_14_05_07](https://cloud.githubusercontent.com/assets/15310985/18846157/a99008c8-83f2-11e6-9dbf-827e50daf0e4.png)

**OSD button text is invisible because of the white text**
![virtualbox_fedora 24 stable_26_09_2016_14_04_55](https://cloud.githubusercontent.com/assets/15310985/18846204/d81a438e-83f2-11e6-84d6-761832aef7ef.png)
- same screenshot: something with row, missing some padding (Identity, Birthdate in screenshot)

**Comment by bluedxca93** [comment]
Okay, thx. all of them also apply to aero. i try to fix this week but can`t
say when exactly.

**Comment by cinnamoner** [comment]
I'm following this one with great interest @bluedxca93 as well.

**Comment by bluedxca93** [comment]
improved scrollbar design today!

**Comment by cinnamoner** [comment]
@bluedxca93 Like the theme.

**Comment by bluedxca93** [comment]
hi do look at ice tommorow.This time for sure i believe and hope.
my new work is time intensive and not much paied. i learn a lot about
hairsstyling. searched before banc-/office-/computer work but the
current job i habe atm.its not that bad and less boring than i tought
it to be.A bit crazy sometimes.

I suppose im able to work on weekends on the themes and mantain current ones.

**Comment by cinnamoner** [comment]
Hello @bluedxca93 old friend, I know what you mean. Don't worry, things will work out for you when least expected. Keep the hope up; you're a really talented and knowledgeable guy. 👍
